
export const SUPPORTED_CURRENCIES = [
  { value: 'AED', label: 'UAE Dirham (AED)', symbol: 'د.إ' },
  { value: 'AFN', label: 'Afghan Afghani (AFN)', symbol: '؋' },
  { value: 'ALL', label: 'Albanian Lek (ALL)', symbol: 'L' },
  { value: 'AMD', label: 'Armenian Dram (AMD)', symbol: '֏' },
  { value: 'ANG', label: 'Netherlands Antillean Guilder (ANG)', symbol: 'ƒ' },
  { value: 'AOA', label: 'Angolan Kwanza (AOA)', symbol: 'Kz' },
  { value: 'ARS', label: 'Argentine Peso (ARS)', symbol: '$' },
  { value: 'AUD', label: 'Australian Dollar (AUD)', symbol: 'A$' },
  { value: 'AWG', label: 'Aruban Florin (AWG)', symbol: 'ƒ' },
  { value: 'AZN', label: 'Azerbaijani Manat (AZN)', symbol: '₼' },
  { value: 'BAM', label: 'Bosnia-Herzegovina Convertible Mark (BAM)', symbol: 'KM' },
  { value: 'BBD', label: 'Barbadian Dollar (BBD)', symbol: '$' },
  { value: 'BDT', label: 'Bangladeshi Taka (BDT)', symbol: '৳' },
  { value: 'BGN', label: 'Bulgarian Lev (BGN)', symbol: 'лв' },
  { value: 'BHD', label: 'Bahraini Dinar (BHD)', symbol: '.د.ب' },
  { value: 'BIF', label: 'Burundian Franc (BIF)', symbol: 'FBu' },
  { value: 'BMD', label: 'Bermudan Dollar (BMD)', symbol: '$' },
  { value: 'BND', label: 'Brunei Dollar (BND)', symbol: '$' },
  { value: 'BOB', label: 'Bolivian Boliviano (BOB)', symbol: 'Bs' },
  { value: 'BRL', label: 'Brazilian Real (BRL)', symbol: 'R$' },
  { value: 'BSD', label: 'Bahamian Dollar (BSD)', symbol: '$' },
  { value: 'BTN', label: 'Bhutanese Ngultrum (BTN)', symbol: 'Nu.' },
  { value: 'BWP', label: 'Botswanan Pula (BWP)', symbol: 'P' },
  { value: 'BYN', label: 'Belarusian Ruble (BYN)', symbol: 'Br' },
  { value: 'BZD', label: 'Belize Dollar (BZD)', symbol: 'BZ$' },
  { value: 'CAD', label: 'Canadian Dollar (CAD)', symbol: 'C$' },
  { value: 'CDF', label: 'Congolese Franc (CDF)', symbol: 'FC' },
  { value: 'CHF', label: 'Swiss Franc (CHF)', symbol: 'CHF' },
  { value: 'CLP', label: 'Chilean Peso (CLP)', symbol: '$' },
  { value: 'CNY', label: 'Chinese Yuan (CNY)', symbol: '¥' },
  { value: 'COP', label: 'Colombian Peso (COP)', symbol: '$' },
  { value: 'CRC', label: 'Costa Rican Colón (CRC)', symbol: '₡' },
  { value: 'CUP', label: 'Cuban Peso (CUP)', symbol: '$' },
  { value: 'CVE', label: 'Cape Verdean Escudo (CVE)', symbol: '$' },
  { value: 'CZK', label: 'Czech Koruna (CZK)', symbol: 'Kč' },
  { value: 'DJF', label: 'Djiboutian Franc (DJF)', symbol: 'Fdj' },
  { value: 'DKK', label: 'Danish Krone (DKK)', symbol: 'kr' },
  { value: 'DOP', label: 'Dominican Peso (DOP)', symbol: 'RD$' },
  { value: 'DZD', label: 'Algerian Dinar (DZD)', symbol: 'دج' },
  { value: 'EGP', label: 'Egyptian Pound (EGP)', symbol: 'E£' },
  { value: 'ERN', label: 'Eritrean Nakfa (ERN)', symbol: 'Nfk' },
  { value: 'ETB', label: 'Ethiopian Birr (ETB)', symbol: 'Br' },
  { value: 'EUR', label: 'Euro (EUR)', symbol: '€' },
  { value: 'FJD', label: 'Fijian Dollar (FJD)', symbol: '$' },
  { value: 'FKP', label: 'Falkland Islands Pound (FKP)', symbol: '£' },
  { value: 'FOK', label: 'Faroese Króna (FOK)', symbol: 'kr' },
  { value: 'GBP', label: 'British Pound (GBP)', symbol: '£' },
  { value: 'GEL', label: 'Georgian Lari (GEL)', symbol: '₾' },
  { value: 'GGP', label: 'Guernsey Pound (GGP)', symbol: '£' },
  { value: 'GHS', label: 'Ghanaian Cedi (GHS)', symbol: 'GH₵' },
  { value: 'GIP', label: 'Gibraltar Pound (GIP)', symbol: '£' },
  { value: 'GMD', label: 'Gambian Dalasi (GMD)', symbol: 'D' },
  { value: 'GNF', label: 'Guinean Franc (GNF)', symbol: 'FG' },
  { value: 'GTQ', label: 'Guatemalan Quetzal (GTQ)', symbol: 'Q' },
  { value: 'GYD', label: 'Guyanaese Dollar (GYD)', symbol: '$' },
  { value: 'HKD', label: 'Hong Kong Dollar (HKD)', symbol: 'HK$' },
  { value: 'HNL', label: 'Honduran Lempira (HNL)', symbol: 'L' },
  { value: 'HRK', label: 'Croatian Kuna (HRK)', symbol: 'kn' },
  { value: 'HTG', label: 'Haitian Gourde (HTG)', symbol: 'G' },
  { value: 'HUF', label: 'Hungarian Forint (HUF)', symbol: 'Ft' },
  { value: 'IDR', label: 'Indonesian Rupiah (IDR)', symbol: 'Rp' },
  { value: 'ILS', label: 'Israeli Shekel (ILS)', symbol: '₪' },
  { value: 'IMP', label: 'Isle of Man Pound (IMP)', symbol: '£' },
  { value: 'INR', label: 'Indian Rupee (INR)', symbol: '₹' },
  { value: 'IQD', label: 'Iraqi Dinar (IQD)', symbol: 'ع.د' },
  { value: 'IRR', label: 'Iranian Rial (IRR)', symbol: '﷼' },
  { value: 'ISK', label: 'Icelandic Króna (ISK)', symbol: 'kr' },
  { value: 'JEP', label: 'Jersey Pound (JEP)', symbol: '£' },
  { value: 'JMD', label: 'Jamaican Dollar (JMD)', symbol: 'J$' },
  { value: 'JOD', label: 'Jordanian Dinar (JOD)', symbol: 'د.ا' },
  { value: 'JPY', label: 'Japanese Yen (JPY)', symbol: '¥' },
  { value: 'KES', label: 'Kenyan Shilling (KES)', symbol: 'KSh' },
  { value: 'KGS', label: 'Kyrgystani Som (KGS)', symbol: 'лв' },
  { value: 'KHR', label: 'Cambodian Riel (KHR)', symbol: '៛' },
  { value: 'KMF', label: 'Comorian Franc (KMF)', symbol: 'CF' },
  { value: 'KPW', label: 'North Korean Won (KPW)', symbol: '₩' },
  { value: 'KRW', label: 'South Korean Won (KRW)', symbol: '₩' },
  { value: 'KWD', label: 'Kuwaiti Dinar (KWD)', symbol: 'د.ك' },
  { value: 'KYD', label: 'Cayman Islands Dollar (KYD)', symbol: '$' },
  { value: 'KZT', label: 'Kazakhstani Tenge (KZT)', symbol: '₸' },
  { value: 'LAK', label: 'Laotian Kip (LAK)', symbol: '₭' },
  { value: 'LBP', label: 'Lebanese Pound (LBP)', symbol: 'ل.ل' },
  { value: 'LKR', label: 'Sri Lankan Rupee (LKR)', symbol: '₨' },
  { value: 'LRD', label: 'Liberian Dollar (LRD)', symbol: '$' },
  { value: 'LSL', label: 'Lesotho Loti (LSL)', symbol: 'L' },
  { value: 'LYD', label: 'Libyan Dinar (LYD)', symbol: 'ل.د' },
  { value: 'MAD', label: 'Moroccan Dirham (MAD)', symbol: 'د.م.' },
  { value: 'MDL', label: 'Moldovan Leu (MDL)', symbol: 'L' },
  { value: 'MGA', label: 'Malagasy Ariary (MGA)', symbol: 'Ar' },
  { value: 'MKD', label: 'Macedonian Denar (MKD)', symbol: 'ден' },
  { value: 'MMK', label: 'Myanma Kyat (MMK)', symbol: 'K' },
  { value: 'MNT', label: 'Mongolian Tugrik (MNT)', symbol: '₮' },
  { value: 'MOP', label: 'Macanese Pataca (MOP)', symbol: 'MOP$' },
  { value: 'MRU', label: 'Mauritanian Ouguiya (MRU)', symbol: 'UM' },
  { value: 'MUR', label: 'Mauritian Rupee (MUR)', symbol: '₨' },
  { value: 'MVR', label: 'Maldivian Rufiyaa (MVR)', symbol: '.ރ' },
  { value: 'MWK', label: 'Malawian Kwacha (MWK)', symbol: 'MK' },
  { value: 'MXN', label: 'Mexican Peso (MXN)', symbol: '$' },
  { value: 'MYR', label: 'Malaysian Ringgit (MYR)', symbol: 'RM' },
  { value: 'MZN', label: 'Mozambican Metical (MZN)', symbol: 'MT' },
  { value: 'NAD', label: 'Namibian Dollar (NAD)', symbol: '$' },
  { value: 'NGN', label: 'Nigerian Naira (NGN)', symbol: '₦' },
  { value: 'NIO', label: 'Nicaraguan Córdoba (NIO)', symbol: 'C$' },
  { value: 'NOK', label: 'Norwegian Krone (NOK)', symbol: 'kr' },
  { value: 'NPR', label: 'Nepalese Rupee (NPR)', symbol: '₨' },
  { value: 'NZD', label: 'New Zealand Dollar (NZD)', symbol: 'NZ$' },
  { value: 'OMR', label: 'Omani Rial (OMR)', symbol: '﷼' },
  { value: 'PAB', label: 'Panamanian Balboa (PAB)', symbol: 'B/.' },
  { value: 'PEN', label: 'Peruvian Sol (PEN)', symbol: 'S/' },
  { value: 'PGK', label: 'Papua New Guinean Kina (PGK)', symbol: 'K' },
  { value: 'PHP', label: 'Philippine Peso (PHP)', symbol: '₱' },
  { value: 'PKR', label: 'Pakistani Rupee (PKR)', symbol: '₨' },
  { value: 'PLN', label: 'Polish Złoty (PLN)', symbol: 'zł' },
  { value: 'PYG', label: 'Paraguayan Guarani (PYG)', symbol: 'Gs' },
  { value: 'QAR', label: 'Qatari Riyal (QAR)', symbol: '﷼' },
  { value: 'RON', label: 'Romanian Leu (RON)', symbol: 'lei' },
  { value: 'RSD', label: 'Serbian Dinar (RSD)', symbol: 'Дин.' },
  { value: 'RUB', label: 'Russian Ruble (RUB)', symbol: '₽' },
  { value: 'RWF', label: 'Rwandan Franc (RWF)', symbol: 'R₣' },
  { value: 'SAR', label: 'Saudi Riyal (SAR)', symbol: '﷼' },
  { value: 'SBD', label: 'Solomon Islands Dollar (SBD)', symbol: '$' },
  { value: 'SCR', label: 'Seychellois Rupee (SCR)', symbol: '₨' },
  { value: 'SDG', label: 'Sudanese Pound (SDG)', symbol: 'ج.س.' },
  { value: 'SEK', label: 'Swedish Krona (SEK)', symbol: 'kr' },
  { value: 'SGD', label: 'Singapore Dollar (SGD)', symbol: 'S$' },
  { value: 'SHP', label: 'Saint Helena Pound (SHP)', symbol: '£' },
  { value: 'SLE', label: 'Sierra Leonean Leone (SLE)', symbol: 'Le' },
  { value: 'SLL', label: 'Sierra Leonean Leone (SLL)', symbol: 'Le' },
  { value: 'SOS', label: 'Somali Shilling (SOS)', symbol: 'S' },
  { value: 'SRD', label: 'Surinamese Dollar (SRD)', symbol: '$' },
  { value: 'SSP', label: 'South Sudanese Pound (SSP)', symbol: '£' },
  { value: 'STN', label: 'São Tomé and Príncipe Dobra (STN)', symbol: 'Db' },
  { value: 'SYP', label: 'Syrian Pound (SYP)', symbol: '£' },
  { value: 'SZL', label: 'Swazi Lilangeni (SZL)', symbol: 'E' },
  { value: 'THB', label: 'Thai Baht (THB)', symbol: '฿' },
  { value: 'TJS', label: 'Tajikistani Somoni (TJS)', symbol: 'SM' },
  { value: 'TMT', label: 'Turkmenistani Manat (TMT)', symbol: 'T' },
  { value: 'TND', label: 'Tunisian Dinar (TND)', symbol: 'د.ت' },
  { value: 'TOP', label: 'Tongan Paʻanga (TOP)', symbol: 'T$' },
  { value: 'TRY', label: 'Turkish Lira (TRY)', symbol: '₺' },
  { value: 'TTD', label: 'Trinidad and Tobago Dollar (TTD)', symbol: 'TT$' },
  { value: 'TVD', label: 'Tuvaluan Dollar (TVD)', symbol: '$' },
  { value: 'TWD', label: 'Taiwan New Dollar (TWD)', symbol: 'NT$' },
  { value: 'TZS', label: 'Tanzanian Shilling (TZS)', symbol: 'TSh' },
  { value: 'UAH', label: 'Ukrainian Hryvnia (UAH)', symbol: '₴' },
  { value: 'UGX', label: 'Ugandan Shilling (UGX)', symbol: 'USh' },
  { value: 'USD', label: 'US Dollar (USD)', symbol: '$' },
  { value: 'UYU', label: 'Uruguayan Peso (UYU)', symbol: '$U' },
  { value: 'UZS', label: 'Uzbekistan Som (UZS)', symbol: 'лв' },
  { value: 'VED', label: 'Venezuelan Bolívar Soberano (VED)', symbol: 'Bs.S' },
  { value: 'VES', label: 'Venezuelan Bolívar Soberano (VES)', symbol: 'Bs.S' },
  { value: 'VND', label: 'Vietnamese Dong (VND)', symbol: '₫' },
  { value: 'VUV', label: 'Vanuatu Vatu (VUV)', symbol: 'VT' },
  { value: 'WST', label: 'Samoan Tala (WST)', symbol: 'WS$' },
  { value: 'XAF', label: 'CFA Franc BEAC (XAF)', symbol: 'FCFA' },
  { value: 'XCD', label: 'East Caribbean Dollar (XCD)', symbol: '$' },
  { value: 'XDR', label: 'Special Drawing Rights (XDR)', symbol: 'SDR' },
  { value: 'XOF', label: 'CFA Franc BCEAO (XOF)', symbol: 'CFA' },
  { value: 'XPF', label: 'CFP Franc (XPF)', symbol: '₣' },
  { value: 'YER', label: 'Yemeni Rial (YER)', symbol: '﷼' },
  { value: 'ZAR', label: 'South African Rand (ZAR)', symbol: 'R' },
  { value: 'ZMW', label: 'Zambian Kwacha (ZMW)', symbol: 'ZK' },
  { value: 'ZWL', label: 'Zimbabwean Dollar (ZWL)', symbol: 'Z$' }
] as const;

export const getCurrencySymbol = (currencyCode: string): string => {
  const currency = SUPPORTED_CURRENCIES.find(c => c.value === currencyCode);
  return currency?.symbol || currencyCode;
};

export const getCurrencyLabel = (currencyCode: string): string => {
  const currency = SUPPORTED_CURRENCIES.find(c => c.value === currencyCode);
  return currency?.label || currencyCode;
};
