// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://lykukadtlhptlskrocux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5a3VrYWR0bGhwdGxza3JvY3V4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM5MzgzMzEsImV4cCI6MjA0OTUxNDMzMX0.w-HRSLGr2vASi_35kWMxmTmY5iNb9l77R8oV0p8PjUg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);